import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import Container from "@/components/Container"

export const metadata = {
  title: "Terms of Service | MUR Solutions",
  description: "Terms and conditions for use of the MUR Solutions SaaS platform.",
}

const sections = [
  {
    id: "subject",
    title: "1. Subject Matter & Parties",
    content: `These Terms of Service ("Terms") govern access to and use of the MUR Solutions SaaS analytics and management platform ("Service") offered by **MUR Solutions S.L.** ("Provider") to restaurant and hospitality operators who subscribe to the Service ("Customer").

**Provider details:**
- Legal name: MUR Solutions S.L.
- Tax ID (CIF): B19837715
- Registered address: Torrent de l'Olla 121, 08012 Barcelona, Spain
- Contact: legal@mur-solutions.com

By activating an account or using the platform, the Customer agrees to be bound by these Terms. This service is intended exclusively for business operators aged 18 or over.`,
  },
  {
    id: "service",
    title: "2. Service Description",
    content: `MUR Solutions provides a real-time analytics, reporting, and AI automation platform for restaurant and hospitality operators. Features include:

- Live sales and operational metrics dashboard
- Automated performance reports per venue
- AI agents for operations automation
- Data export in structured formats

**Informational nature:** All analyses, forecasts, and reports generated by the platform are for **informational purposes only**. MUR Solutions does not guarantee specific business outcomes. Business decisions made based on platform data are the Customer's sole responsibility.`,
  },
  {
    id: "subscription",
    title: "3. Subscription & Pricing",
    content: `The Service is provided via monthly subscription per venue:

- **Base price:** $500 USD per venue / month
- Billed monthly in advance
- Prices exclude applicable taxes (VAT 21% in Spain)
- Price changes require a minimum of **60 days' written notice** by email

Subscriptions auto-renew monthly until cancelled by the Customer.`,
  },
  {
    id: "payment",
    title: "4. Payment & Billing",
    content: `- Payments are processed via the payment processor enabled on the platform.
- In the event of non-payment, access may be suspended after **7 days** from the due date.
- The Customer will receive electronic invoices in accordance with Spanish tax regulations.
- Billing disputes must be raised within **30 days** of the invoice date.`,
  },
  {
    id: "cancellation",
    title: "5. Cancellation",
    content: `The Customer may cancel their subscription at any time via account settings or by emailing **legal@mur-solutions.com**.

**Effects of cancellation:**
- Access remains active until the end of the current billing period.
- No partial refunds are issued.
- After cancellation, restaurant operational data is available for export for **30 days**, after which it is permanently deleted.

The Provider may cancel or suspend the Service for breach of these Terms with **15 days' notice**, except in cases of serious breach.`,
  },
  {
    id: "data",
    title: "6. Data Ownership",
    content: `**The Customer is the exclusive owner of all their data.**

MUR Solutions acts solely as a data processor for the Customer's data under GDPR. The Provider:

- Does not sell, transfer, or monetise Customer data with third parties
- Accesses data only to deliver the contracted Service and provide technical support
- May use anonymised, aggregated data to improve the product, without identifying the Customer or their venues

The Customer warrants that they hold the necessary rights over all data uploaded to the platform and that its use complies with applicable law.`,
  },
  {
    id: "liability",
    title: "7. Limitation of Liability",
    content: `**7.1 Exclusions.** MUR Solutions shall not be liable for:
- Lost profits, indirect damages, or business losses arising from use of platform analytics or reports
- Commercial decisions made by the Customer based on platform data
- Interruptions to third-party services (infrastructure providers, payment processors)
- Data loss caused by the Customer

**7.2 Cap.** In any event, the Provider's maximum aggregate liability to the Customer shall not exceed the amounts paid by the Customer in the **3 months preceding the event** giving rise to the claim.

**7.3 Availability.** The Provider targets **99.5% monthly uptime** (excluding scheduled maintenance with prior notice). Uninterrupted availability is not guaranteed.`,
  },
  {
    id: "ip",
    title: "8. Intellectual Property",
    content: `The platform, source code, design, brand, and documentation are the exclusive property of MUR Solutions S.L. and are protected by applicable intellectual property law.

The Customer receives a **limited, non-exclusive, non-transferable licence** to access and use the platform during their active subscription.

Reverse engineering, copying, distributing, or creating derivative works from the platform is prohibited without the Provider's express written consent.`,
  },
  {
    id: "confidentiality",
    title: "9. Confidentiality",
    content: `Both parties agree to keep the other party's non-public information confidential. This obligation extends for **2 years** after the end of the contractual relationship.`,
  },
  {
    id: "modifications",
    title: "10. Modifications to These Terms",
    content: `The Provider may modify these Terms by notifying the Customer at least **30 days in advance** by email. Continued use of the Service after that period constitutes acceptance of the updated Terms.

Last updated: **May 2025**`,
  },
  {
    id: "law",
    title: "11. Governing Law & Jurisdiction",
    content: `These Terms are governed by Spanish law. For any dispute, the parties submit to the **Courts and Tribunals of Madrid**, expressly waiving any other jurisdiction that may apply.`,
  },
]

function renderLine(line: string, i: number) {
  if (line.startsWith("**") && line.endsWith("**")) {
    return (
      <p key={i} className="font-semibold text-white mt-4 mb-1">
        {line.replace(/\*\*/g, "")}
      </p>
    )
  }
  if (line.startsWith("- **")) {
    const match = line.match(/^- \*\*(.+?)\*\*(.*)$/)
    if (match) {
      return (
        <p key={i} className="ml-4 mb-1">
          <span className="text-accent font-medium">• {match[1]}</span>
          <span>{match[2]}</span>
        </p>
      )
    }
  }
  if (line.startsWith("- ")) {
    return <p key={i} className="ml-4 mb-1">• {line.slice(2)}</p>
  }
  if (line.trim() === "") return <div key={i} className="h-2" />
  if (line.includes("**")) {
    const parts = line.split(/\*\*/)
    return (
      <p key={i} className="mb-1">
        {parts.map((part, j) =>
          j % 2 === 1 ? <span key={j} className="text-white font-semibold">{part}</span> : part
        )}
      </p>
    )
  }
  return <p key={i} className="mb-1">{line}</p>
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20 min-h-screen">
        <Container>
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 bg-accent/10 border border-accent/30 rounded-full px-4 py-2 mb-6">
              <span className="text-accent text-sm font-inter font-medium">Legal</span>
            </div>
            <h1 className="font-montserrat font-bold text-3xl md:text-4xl lg:text-5xl text-white mb-4">
              Terms of Service
            </h1>
            <p className="font-inter text-lg text-grayL max-w-2xl mx-auto">
              Terms and conditions for use of the MUR Solutions SaaS platform for restaurant operators
            </p>
          </div>

          <div className="max-w-4xl mx-auto space-y-6">
            {sections.map((section) => (
              <div
                key={section.id}
                className="bg-navy/50 border border-grayD/30 hover:border-accent/30 transition-colors duration-300 rounded-xl p-8"
              >
                <h2 className="font-montserrat font-semibold text-xl text-accent mb-4">{section.title}</h2>
                <div className="font-inter text-grayL leading-relaxed text-sm">
                  {section.content.split("\n").map((line, i) => renderLine(line, i))}
                </div>
              </div>
            ))}
          </div>
        </Container>
      </main>
      <Footer />
    </>
  )
}
